export enum ResourceType {
    GOLD_COIN,

    RAW_MATERIAL_CLAY,
    RAW_MATERIAL_ORE,
    RAW_MATERIAL_STONE,
    RAW_MATERIAL_WOOD,

    MANUFACTURED_GOOD_GLASS,
    MANUFACTURED_GOOD_PAPYRUS,
    MANUFACTURED_GOOD_TEXTILES,
}